linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - bodyclose
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: false
  staticcheck:
    checks: ["all"]

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
