package dto

type TaskType string

const (
	TaskTypeBackup        TaskType = "backup"
	TaskTypeMeasureSize   TaskType = "measure_size"
	TaskTypeGetDiskUsage  TaskType = "get_disk_usage"
	TaskTypeSearchFiles   TaskType = "search_files"
	TaskTypeRestoreLocal  TaskType = "restore_local"
	TaskTypeListFiles     TaskType = "list_files"
	TaskTypeRestoreRemote TaskType = "restore_remote"
	TaskTypePurge         TaskType = "purge"
)

type WorkerTask struct {
	Type     TaskType `json:"type"`
	TaskID   string   `json:"task_id"`
	BackupID string   `json:"backup_id,omitempty"`
	JobID    string   `json:"job_id"`
	Host     string   `json:"host"`
	User     string   `json:"user"`
	Port     int      `json:"port"`
	Path     string   `json:"path"`
	// Backup specific
	Destination string     `json:"destination,omitempty"`
	Excludes    []string   `json:"excludes,omitempty"`
	HostPath    string     `json:"host_path,omitempty"`
	Incremental bool       `json:"incremental,omitempty"`
	Retention   int        `json:"retention,omitempty"`
	Encrypted   bool       `json:"encrypted,omitempty"`
	Hooks       []HookTask `json:"hooks,omitempty"`
	// Search specific
	SearchPattern string `json:"search_pattern,omitempty"`
	// Restore local specific
	RestoreAddr  string `json:"restore_addr,omitempty"`  // IP:Port of the CLI
	RestoreToken string `json:"restore_token,omitempty"` // Auth token generated by CLI
	// Restore remote specific
	TargetHost string `json:"target_host,omitempty"`
	TargetUser string `json:"target_user,omitempty"`
	TargetPort int    `json:"target_port,omitempty"`
	TargetPath string `json:"target_path,omitempty"`
}

type HookTask struct {
	Name    string            `json:"name"`
	Phase   string            `json:"phase"`
	Params  map[string]string `json:"params"`
	Enabled bool              `json:"enabled"`
}
